package com.iot.panel.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.iot.panel.db.FormOne;

import com.iot.panel.db.FormOneDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig formOneDaoConfig;

    private final FormOneDao formOneDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        formOneDaoConfig = daoConfigMap.get(FormOneDao.class).clone();
        formOneDaoConfig.initIdentityScope(type);

        formOneDao = new FormOneDao(formOneDaoConfig, this);

        registerDao(FormOne.class, formOneDao);
    }
    
    public void clear() {
        formOneDaoConfig.clearIdentityScope();
    }

    public FormOneDao getFormOneDao() {
        return formOneDao;
    }

}
